kafka:
  bootstrapServers: localhost:9092
  schemaRegistry: http://localhost:8081
  snapshotTopic: telemetry.snapshots.v1
  hubTopic: telemetry.hubs.v1
  snapshotGroup: analyzer-snapshots
  hubGroup: analyzer-hubs

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      negotiationType: plaintext

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
