spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

analyzer:
  topics:
    hubs: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1
server:
  port: 8080

collector:
  topics:
    hubs: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1
